### ISSUE TITLE
TypeError: i18nextJquery.init is not a function. 

### ISSUE THREAD

**Issue by prtome** [i18next/jquery-i18next#10]
Hello,
I have downloaded the zip from the repository, and added i18next-jquery.min.js to my page,
It gives me that error message: 
TypeError: i18nextJquery.init is not a function. (In 'i18nextJquery.init', 'i18nextJquery.init' is undefined)

I tried with the example in the repository, if I replace the cdnjs address by the local i18next-jquery.min.js
I have the same error. 

my code works also works if I call the cdnjs version instead of the local one
any idea ? 

thanks

**Comment by jamuhl** [comment]
try https://github.com/i18next/jquery-i18next/blob/master/i18next-jquery.min.js the global i18nextJquery gets set if not using any module loader - as i remember that's the case in your app.

**Comment by pfanners** [comment]
No - The object is not properly attached to the global scope.

change (jquery-i18next.min.js)
`define.amd?define("jquery-i18next",e):t.jquery-i18next=e()}`
to:
`define.amd?define("i18nextJquery",e):t.i18nextJquery=e()}`

or jquery-i18next.js
change line 3 - 4

```
typeof define === 'function' && define.amd ? define('jquery-i18next', factory) :
(global.jquery-i18next = factory());
```

to 

```
typeof define === 'function' && define.amd ? define('i18nextJquery', factory) :
(global.i18nextJquery = factory());

```

so long
Florian Pfann

**Comment by jamuhl** [comment]
@pfanners  this is a change introduced yesterday

changed readme to reflect that change
