### ISSUE TITLE
Error: "Invalid left-hand side in assignment"

### ISSUE THREAD

**Issue by turkelinda** [i18next/jquery-i18next#11]
In the file jquery-i18next.js in line 4 you wrote:
global.jquery-i18next = factory()
there i get an error: "Uncaught ReferenceError: Invalid left-hand side in assignment(…)"
i think the a name with "-" is not working
i tried to fix it locally like that: global['jquery-i18next'] = factory()
-> it works again

Thanks

**Comment by jamuhl** [comment]
argh...that's no good...let me rename this to `global.jqueryI18next`....will publish an update in a few seconds.

**Comment by jamuhl** [comment]
just published v0.2.0

**Comment by turkelinda** [comment]
cool thanks that was quick!
I can see the new version in GIT but not in npm.
Did you publish it to npm yet?

Thanks

**Comment by jamuhl** [comment]
forgot to publish...done now...

**Comment by turkelinda** [comment]
thanks it works
