### ISSUE TITLE
Strings with ":" character inside will not be translated client-side

### ISSUE THREAD

**Issue by TitaneBoy** [i18next/jquery-i18next#12]
Hi.
I was trying your jquery-i18next module and I noticed that if a string contains the character ":", the translation will not be made. When we activate the debug option, we can see in the console log that it tries to translate the string without the ":" character. And because in the json resource file the string contains the ":" character, i18next don't find the translation for that string. 

For example, if I have this line: 

`<title class="MyTest" data-i18n="Yeeahh: My First Translated Web Page"></title>`

jquery-i18next will try to translate `"Yeeahh  My First Translated Web Page"` (without the ":" character) instead of `"Yeeahh: My First Translated Web Page"` (with the ":" character)

(or maybe it tries to translate only the string in the right-side of the ":" character:  `"My First Translated Web Page"` )

Here is what we can find in the json resource file (for french language for example)

```
{
    "Yeaahh: My First Translated Web Page": "Yeaahh: Ma première page web traduite",
    "Choose your favorite application:": "Choisissez votre application favorite:"
}

```

And Here is my web page (HTML):

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US">
    <head>
      <script type="text/javascript" src="lib/i18next.js"></script>
      <script type="text/javascript" src="lib/i18nextXHRBackend.js"></script>
      <script type="text/javascript" src="lib/i18nextBrowserLanguageDetector.js"></script>
      <script type="text/javascript" src="lib/jquery.min.js"></script>
      <script type="text/javascript" src="lib/jquery-i18next.min.js"></script>

      <script type="text/javascript">
        var i18nextOptions = {
                              load:['en-US', 'fr', 'es'],
                              whitelist:['en-US', 'fr', 'es'],
                              fallbackLng: 'en-US',
                              ns:'Web_Server',
                              defaultNS:'Web_Server',
                              backend: {loadPath: '/language/static/{{lng}}/{{ns}}.json', addPath: 'language/static/add/{{lng}}/{{ns}}.json'},
                              detection: {order: ['querystring', 'cookie', 'navigator', 'localStorage'],
                                          lookupQuerystring: 'lng',
                                          lookupCookie: 'i18next',
                                          lookupLocalStorage: 'i18nextLng',
                                          caches: ['localStorage', 'cookie'],
                                          cookieMinutes: 5},
                              debug: true
                             };
        i18next
          .use(i18nextXHRBackend)
          .use(i18nextBrowserLanguageDetector)
          .init(i18nextOptions, function(err, t){

            jqueryI18next.init(i18next, $);

            $('.MyTest').localize();
          });

      </script>

      <meta http-equiv="Content-Type" content="text/html; charset=utf8" />
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      <title class="MyTest" data-i18n="Yeaahh: My First Translated Web Page"></title>
      <link rel="stylesheet" href="lib/bootstrap-3.1.1/css/bootstrap.min.css">
      <link rel="stylesheet" href="lib/bootstrap-3.1.1/css/bootstrap-theme.min.css">
      <link rel="stylesheet" href="css/style.css"/>

    </head>
```

And Finally, this is what we can see in the console log:

```
i18next::backendConnector: loaded namespace My_Web_Server for language fr Object
i18next.js:111 i18next::backendConnector: loaded namespace My_Web_Server for language en-US Object
i18next: languageChanged fr
i18next: initialized Object {debug: true, ns: Array[1], defaultNS: "My_Web_Server", fallbackLng: Array[1], fallbackNS: false…}
i18next::translator: missingKey fr Yeeahh  My First Translated Web Page  My First Translated Web Page
i18next::translator: missingKey fr Choose your favorite application        

```

For the string "Yeeahh: My First Translated Web Page", in the console log, I don't know if it's an error from the module, but the log looks a little bit weird:

`i18next::translator: missingKey fr Yeeahh  My First Translated Web Page  My First Translated Web Page`

You can see that "My First Translated Web Page" is repeated twice. It's not so bad but for the eyes, you know... ;-)

Thank you in advance for your answer :-)

**Comment by TitaneBoy** [comment]
I was wondering: How can we do sprintf-postProcessor in the client-side ?

In the server-side, it's very easy to do that.. But I don't know how we can use sprintf strings with jquery-i18next module in the client-side (i.e in the HTML file) .

Can you help me please with that point ?

Thank you again

**Comment by jamuhl** [comment]
`i18next::translator: missingKey fr Yeeahh  My First Translated Web Page  My First Translated Web Page`

= `i18next::translator: missingKey {{lng}} {{key}}  {{value}}`

sprintf usage is same as on serverside...add it by `use` then call `localize({ postProcess: 'sprintf', sprintf: {...} })` with correct translation options: https://github.com/i18next/i18next-sprintf-postProcessor#usage-sample

**Comment by TitaneBoy** [comment]
Hi jamuhl. Thank you for your answer.

Can you confirm me please that the case with the ":" character inside the string to translate, which is not translated at all, is an issue ?

Thank you in advance.

**Comment by jamuhl** [comment]
':' and '.' are special characters to separate namesapce and keys. 

see http://i18next.com/translate/keyBasedFallback/ for options to disable them.

**Comment by TitaneBoy** [comment]
Thanks. But now, I tested the sprintf post processor and it looks to work well (in the javascript environment (or server-side). But I was wondering How to use it inside an html tag, with for example the data-i18n

Example:
In.json file:

```
{
    "by %s": "par %s"
}
```

In HTML file:

`<button type="button" class="btn btn-success MyTest" data-i18n="by %s"> <a href="/user/login"> WebMail <br> </a></button>`

In javascript environment, I know that to translate "by %s", I have to do this:

`i18next.t('by %s', {postProcess:'sprintf', sprintf:['A User Name']})`

But in the HTML tag, like you can see in my example, I'm just not sure how to make this work.

Thank you again for your help, your answer and your patience with me .

**Comment by jamuhl** [comment]
https://github.com/i18next/jquery-i18next#using-options-in-translation-function

you can pass options inside calling .localize(opts) or on attribute `data-i18n-options` on the element to be translated

**Comment by TitaneBoy** [comment]
Hi Jamuhl.

As you have suggested me, I passed options on attribute data-i18n-options but with no sucess. I initialized the jqueryI18next with the "`{useOptionsAttr: true}`" as described in [https://github.com/i18next/jquery-i18next#using-options-in-translation-function](url)

But the sprintf post process still not working. I found that the init function of jquery-i18next module doesn't have a fallback function, like the init function of your i18next module. I guess that it is not working because of the asynchronous nature of nodejs.

This is what I have done in my HTML file:

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US">
    <head>
      <script type="text/javascript" src="lib/i18next.js"></script>
      <script type="text/javascript" src="lib/i18nextXHRBackend.js"></script>
      <script type="text/javascript" src="lib/i18nextBrowserLanguageDetector.js"></script>
      <script type="text/javascript" src="lib/jquery.min.js"></script>
      <script type="text/javascript" src="lib/jquery-i18next.min.js"></script>      

      <meta http-equiv="Content-Type" content="text/html; charset=utf8" />
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">

      <title class="MyTest" data-i18n="Yeaahh: My First Translated Web Page"></title>
      <link rel="stylesheet" href="lib/bootstrap-3.1.1/css/bootstrap.min.css">
      <link rel="stylesheet" href="lib/bootstrap-3.1.1/css/bootstrap-theme.min.css">
      <link rel="stylesheet" href="css/style.css"/>

    </head>

    <body>
        <p style="text-align:center">
            <button type="button" class="btn btn-success MyTest" data-i18n="WebMail <br> by %s" i18n-options="{postProcess:'sprintf', sprintf:['A User Name']}"> <a href="/user/login"></a></button>
        </p>

        <script type="text/javascript">
            var i18nextOptions = {
                                  load:['en-US', 'fr', 'es'],
                                  whitelist:['en-US', 'fr', 'es'],
                                  fallbackLng: 'en-US',
                                  ns:'Web_Server',
                                  defaultNS:'Web_Server',
                                  backend: {loadPath: '/language/static/{{lng}}/{{ns}}.json', addPath: 'language/static/add/{{lng}}/{{ns}}.json'},
                                  detection: {order: ['querystring', 'cookie', 'navigator', 'localStorage'],
                                              lookupQuerystring: 'lng',
                                              lookupCookie: 'i18next',
                                              lookupLocalStorage: 'i18nextLng',
                                              caches: ['localStorage', 'cookie'],
                                              cookieMinutes: 5},
                                  debug: true
                                 };
            i18next
              .use(i18nextXHRBackend)
              .use(i18nextBrowserLanguageDetector)
              .use(i18nextSprintfPostProcessor)
              .init(i18nextOptions, function(err, t){

                jqueryI18next.init(i18next, $, {useOptionsAttr: true}, function(err, t){
                  var NewValue = i18next.t('WebMail <br> by %s', {postProcess:'sprintf', sprintf:['A userName']});
                  console.log("NewValue = " + NewValue);
                });
                console.log("Test printing");

                $('.MyTest').localize();
              });

        </script>
    </body>
```

As you can see at the end, I initialized jqueryI18next:

```
 jqueryI18next.init(i18next, $, {useOptionsAttr: true}, function(err, t){
                  var NewValue = i18next.t('WebMail <br> by %s', {postProcess:'sprintf', sprintf:['A userName']});
                  console.log("NewValue = " + NewValue);
                });
                console.log("Test printing");
```

 and I tried to get a new value in a fallback function but as I said before, I discovered that this init function doesn't have one.

So when I refresh my web page, I can see the following text in my button:

`WebMail <br> par %s`. 

We can see that `"WebMail <br> by %s"` has been translated successfully but the sprintf post-process didn't work. I expected to see in my button the following text: `"WebMail <br> par A userName"`.

Can you tell me please what I am doing wrong or if there are an issue in the jquery-i18next module ?

Thank you again for your answer and your help.

PS:
In the jquery-i18next.js file of your module, we can found this:

```
var defaults = {
    tName: 't',
    i18nName: 'i18n',
    handleName: 'localize',
    selectorAttr: 'data-i18n',
    targetAttr: 'i18n-target',
    optionsAttr: 'i18n-options',
    useOptionsAttr: false,
    parseDefaultValueFromContent: true
  };
```

but in the web-site of your module, this is what is written:

```
i18nextJquery.init(i18nextInstance, $, {
  tName: 't', // --> appends $.t = i18next.t
  i18nName: 'i18n', // --> appends $.i18n = i18next
  handleName: 'localize', // --> appends $(selector).localize(opts);
  selectorAttr: 'data-i18n', // selector for translating elements
  targetAttr: 'data-i18n-target', // element attribute to grab target element to translate (if diffrent then itself)
  optionsAttr: 'data-i18n-options', // element attribute that contains options, will load/set if useOptionsAttr = true
  useOptionsAttr: false, // see optionsAttr
  parseDefaultValueFromContent: true // parses default values from content ele.val or ele.text
});
```

The default values of targetAttr and optionsAttr are not updated in the description of your Git website module ( [https://github.com/i18next/jquery-i18next#initialize-the-plugin](url))

**Comment by jamuhl** [comment]
there is no callback in jqueryI18next as it is synchronous:

```
i18next
              .use(i18nextXHRBackend)
              .use(i18nextBrowserLanguageDetector)
              .use(i18nextSprintfPostProcessor)
              .init(i18nextOptions, function(err, t){

                jqueryI18next.init(i18next, $, {useOptionsAttr: true});

               // do it here
               var NewValue = i18next.t('WebMail <br> by %s', {postProcess:'sprintf', sprintf:['A userName']});
               console.log("NewValue = " + NewValue);

               // check if your data option attribute is valid
               console.log($('.MyTest').data('i18n-options'));

                console.log("Test printing");

                $('.MyTest').localize();
              });

```

**Comment by TitaneBoy** [comment]
Hi jamuhl.

I have done what you told me to try. And the value of "NewValue" is perfectly translated and the sprintf post-process worked well too.

But the text in the button in my HTML file:

```
<p style="text-align:center">
   <button type="button" id="ToTest" class="btn btn-success MyTest" data-i18n="WebMail <br> by %s" i18n-options="{postProcess:'sprintf', sprintf:['A User Name']}"> <a href="/pdalva/login"></a></button>
</p>
```

didn't had the sprintf post-process done on it. We still can see `WebMail <br> par %s` and not `WebMail <br> par A User Name` as expected.

I looked the i18n-options attribute of the button in the console log and it looks that the data inside are correct (I think). This is what I get:

```
i18n-options
    baseURI:"http://localhost/"
    childNodes:NodeList[0]
    firstChild:null
    lastChild:null
    localName:"i18n-options"
    name:"i18n-options"
    namespaceURI:null
    nextSibling:null
    nodeName:"i18n-options"
    nodeType:2
    nodeValue:"{postProcess:'sprintf', sprintf:['A User Name']}"
    ownerDocument:document
    ownerElement:button#ToTest.btn.btn-success.MyTest
    parentElement:null
    parentNode:null
    prefix:null
    previousSibling:null
    specified:true
    textContent:"{postProcess:'sprintf', sprintf:['A User Name']}"
    value:"{postProcess:'sprintf', sprintf:['A User Name']}"
    __proto__:Node
    length:5
```

**Comment by jamuhl** [comment]
I looked the i18n-options attribute of the button in the console log and it looks that the data inside are correct (I think).

Seems not correct to me. `console.log($('.MyTest').data('i18n-options'));` should give you `{postProcess:'sprintf', sprintf:['A User Name']}` as javacript object

best is to:

`$('.MyTest').data('i18n-options', {postProcess:'sprintf', sprintf:['A User Name']})` and see how it should be serialized on the element.

**Comment by TitaneBoy** [comment]
`console.log($('.MyTest').data('i18n-options'));` returns me "undefined" in the console log. I thought that the instruction was not correct so I tried to get the i18n-options object data other way, which gave me what I wrote in my last post.

I tried again an other way to get information. This is what I recently tried:

```
var tempValue = $(".MyTest[i18n-options]").attr("i18n-options");
console.log("i18n-options = " + tempValue);
```

It will search for the html component which contains "MyTest" class and which contains an attribute with the name "i18n-options" (`$(".MyTest[i18n-options]")`). With this object, I  get i18n-options attribute (`.attr("i18n-options");`)

The result of that gives me:  `i18n-options = {postProcess:'sprintf', sprintf:['A User Name']}`

**Comment by jamuhl** [comment]
basically using https://api.jquery.com/data/ so console.log($('.MyTest').data('i18n-options')); should work if correct data

**Comment by TitaneBoy** [comment]
Hi jamuhl. I guess you are right when you are telling that .data() function should work but somehow, it doesn't works for me :-(

I was wondering if you could test it with my HTML file because no matter what I am doing to try to resolve it, It doesn't work...and It's my last step for me before I can go something great and functional. Your help would be really appreciated (and it is already with all your help you gave me )

Here is my resource json File

```
{
    "Welcome to My Web Server !!!": "Bienvenu sur mon serveur Web!!!",
    "Choose your favorite application:": "Choisissez votre application favorite:",
    "Hello":"Bonjour Fr",
    "WebMail":"Email Web",
    "Yeeahh: My First Translated Web Page":"Supeerrr: Ma première page web traduite",
    "WebMail <br> by %s": "WebMail <br> par %s"
}
```

Here is my HTML file

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-US">
    <head>
      <script type="text/javascript" src="lib/i18next.js"></script>
      <script type="text/javascript" src="lib/i18nextXHRBackend.js"></script>
      <script type="text/javascript" src="lib/i18nextBrowserLanguageDetector.js"></script>
      <script type="text/javascript" src="lib/i18nextSprintfPostProcessor.min.js"></script>
      <script type="text/javascript" src="lib/jquery.min.js"></script>
      <script type="text/javascript" src="lib/jquery-i18next.min.js"></script>

      <meta http-equiv="Content-Type" content="text/html; charset=utf8" />
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">

                          <!--  TITLE here  -->

      <title class="MyTest" data-i18n="Yeeahh: My First Translated Web Page"></title>


      <link rel="stylesheet" href="lib/bootstrap-3.1.1/css/bootstrap.min.css">
      <link rel="stylesheet" href="lib/bootstrap-3.1.1/css/bootstrap-theme.min.css">
      <link rel="stylesheet" href="css/style.css"/>

    </head>

    <body background="./img/MS_homepageNEW_bg3.jpg">

        <font color="yellow">
        <h1 class="MyTest" align="center" data-i18n="Welcome to my Web Server !!!"><br><br> </h1>
        </font>

      <p style="text-align:center"><img src = "img/Family.jpg"> </img></p>
        <font color="yellow">
        <h2 align="center" class="MyTest" data-i18n="Choose your favorite application:"> <br> <br> </h2>
        </font>

      <p style="text-align:center">
        <button type="button" id="ToTest" class="btn btn-success MyTest" data-i18n="WebMail <br> by %s" i18n-options="{postProcess:'sprintf', sprintf:['A User Name']}"> <a href="/user/login"></a></button>
      </p>
      <script type="text/javascript">
        var i18nextOptions = {
                              preload:['en-US', 'fr', 'es'],
                              whitelist:['en-US', 'fr', 'es'],
                              fallbackLng: 'en-US',
                              ns:'Rubis_Web_Server',
                              defaultNS:'Rubis_Web_Server',
                              nsSeparator: false,
                              keySeparator: false,
                              backend: {loadPath: '/language/static/{{lng}}/{{ns}}.json', addPath: 'language/static/add/{{lng}}/{{ns}}.json'},
                              detection: {order: ['querystring', 'cookie', 'navigator', 'localStorage'],
                                          lookupQuerystring: 'lng',
                                          lookupCookie: 'i18next',
                                          lookupLocalStorage: 'i18nextLng',
                                          caches: ['localStorage', 'cookie'],
                                          cookieMinutes: 5},
                              debug: true
                             };
        i18next
          .use(i18nextXHRBackend)
          .use(i18nextBrowserLanguageDetector)
          .use(i18nextSprintfPostProcessor)
          .init(i18nextOptions, function(err, t){

            jqueryI18next.init(i18next, $, {useOptionsAttr:true});
            var NewValue = i18next.t('WebMail <br> by %s', {postProcess:'sprintf', sprintf:['A User Name']});
            console.log("NewValue = " + NewValue);            

            // Trying to make your command but it returns me always undefined
            console.log($('.MyTest').data('i18n-options'));

            // Here, tempValue returns me: "i18n-options = {postProcess:'sprintf', sprintf:['A User Name']}"
            var tempValue = $(".MyTest[i18n-options]").attr("i18n-options");
            console.log("i18n-options = " + tempValue);


            $('.MyTest').localize();
          });

      </script>
    </body>
</html>

```

**Comment by jamuhl** [comment]
https://jsfiddle.net/z81ezzpy/1/

```
<button type="button" id="ToTest" class="btn btn-success MyTest" data-i18n="WebMail <br> by %s" data-i18n-options="{postProcess:'sprintf', sprintf:['A User Name']}"> <a href="/user/login"></a></button>
```

--> the attribute is `data-i18n-options` not `i18n-options`

```
 console.log($('#ToTest').data('i18n-options')); // ---> {postProcess:'sprintf', sprintf:['A User Name']}
```

Element with options seems to now by id #ToTest

**Comment by TitaneBoy** [comment]
You are right..It was my mistake. I'm sorry.. Now I can see that `console.log($('#ToTest').data('i18n-options'));` returns me `{postProcess:'sprintf', sprintf:['A User Name']}`.

But even with the following button code (I changed here  i18n-options for **data-i18n-options**) :

`<button type="button" id="ToTest" class="btn btn-success MyTest" data-i18n="WebMail <br> by %s" data-i18n-options="{postProcess:'sprintf', sprintf:['A User Name']}"> <a href="/user/login"></a></button>`

In my web page, the value of this button is `WebMail <br> par %s`  (the sprintf post-process seems to not be applied ).

According to you, what is not working in my code ?

**Comment by jamuhl** [comment]
https://jsfiddle.net/z81ezzpy/2/

`data-i18n-options='{"postProcess": "sprintf", "sprintf":["A User Name"]}'` must be valid json not js

**Comment by TitaneBoy** [comment]
Perfect !!! .Thanks a lot...It works as expected..

THANK YOU VERY MUCH again for your great help and quick answers :-)  :+1:  :100: / :100:
