### ISSUE TITLE
No sprintf post-process done after first loading.

### ISSUE THREAD

**Issue by TitaneBoy** [i18next/jquery-i18next#15]
Hi jamuhl.

I'm facing other issues with the current module.

Here is my context:

I have this function at the end of the "head" Html Tag:

```
<head>
...
    <script>
          function onChangeLanguage() {
              var selectedLanguage = document.getElementById("languageSelect").value;
               $('.MyTest').localize({lng: selectedLanguage});         
          }
    </script>
<head>
```

In the "Body" Html Tag:

```
<select id="languageSelect" class="MyTest" style="float:right;margin-right:20px;margin-top:1px" onchange="onChangeLanguage()">
            <option value="fr" name="language" data-i18n="French" selected></option>
            <option value="en-US" name="language" data-i18n="English"></option>
            <option value="es" name="language" data-i18n="Spanish"></option>
</select>

....
<p style="text-align:center">
        <button type="button" id="ToTest" class="btn btn-success MyTest" data-i18n="WebMail <br> by %s" data-i18n-options='{"postProcess":"sprintf", "sprintf":["A User Name"]}'> <a href="/user/login"></a></button>
</p>
```

And this is my configuration of i18next at the end of the "body" Html Tag:

```
<script type="text/javascript">
        var i18nextOptions = {
                              preload:['en-US','fr', 'es'],
                              whitelist:['en-US','fr', 'es'],
                              fallbackLng: 'en-US',
                              ns:'My_Web_Server',
                              defaultNS:'My_Web_Server',
                              nsSeparator: false,
                              keySeparator: false,
                              backend: {loadPath: '/language/static/{{lng}}/{{ns}}.json', addPath: 'language/static/add/{{lng}}/{{ns}}.json'},
                              detection: {order: ['querystring', 'cookie', 'navigator', 'localStorage'],
                                          lookupQuerystring: 'lng',
                                          lookupCookie: 'i18next',
                                          lookupLocalStorage: 'i18nextLng',
                                          caches: ['localStorage', 'cookie'],
                                          cookieMinutes: 5},
                              debug: false
                             };
        i18next
          .use(i18nextXHRBackend)
          .use(i18nextBrowserLanguageDetector)
          .use(i18nextSprintfPostProcessor)
          .init(i18nextOptions, function(err, t){

            jqueryI18next.init(i18next, $, {useOptionsAttr:true});
            $('.MyTest').localize();
          });
</script>
```

Well..When the page is first loaded, everything works great. But when I change the value of the dropdown (Français to Anglais )  (i.e French to English), the content of the button is translated, but the sprintf-post process seems to not working. Of course, As you can see, when the value of the dropdown is changed, it will call the javascript function "onChangeLanguage()". In this function, I'm taking the new selected value ("en-US", "fr" or "es") and I am calling $('.MyTest').localize() with in option the new language to use.  But as I said, the

`WebMail <br> by %s` is well translated, but at the end, the sprintf post process doesn't work.

What can I do to fix this ? Is it an issue from the module ?

Thank you for your answer :-)

**Comment by jamuhl** [comment]
having data-options will override passed options to localize().

call i18next.changeLanguage and localize after that without lng in option.

**Comment by TitaneBoy** [comment]
Wow..Great..It works very well...Thank you...:-)
Last question if you allow me: 

As you saw, I have the following html button:

`<button type="button" id="butt1" class="btn btn-success MyTest" data-i18n="[html]WebMail <br> by %s" data-i18n-options='{"postProcess":"sprintf", "sprintf":["A User Name"]}'> <a href="/user/login"></a></button>`

I was wondering what I can do to have the << **'** >> character in the string used by the sprintf. For example, I want  to replace "A User Name" by "First**'**s name " (Notice the **'** character inside). I've tried a lot of combinaison but because the character **'** is used to define strings, my combinaisons don't work and I'm not sure of what to do to resolve it. This is basically what I want to do:

`data-i18n-options='{"postProcess":"sprintf", "sprintf":["First's Name"]}'`

But It will not work because of the ' character after the string "First"

I found another way with `&#39;` :

`data-i18n-options='{"postProcess":"sprintf", "sprintf":["First&#39;s Name"]}'` (Notice here the "`&#39;`" after the string "First")

I was wondering if there are another way (than using `&#39;`) to have the ' (apostrophe) character inside the string.

`"{'postProcess':'sprintf', 'sprintf':['First Name']}"`  (Here, I inverted/reversed " to ' ) doesn't work, even without apostrophe character inside the string used by the sprintf.

Thank you for your answer.

**Comment by jamuhl** [comment]
not sure might be encode by using `\'` works too...else `&#39;` is the way to go...

**Comment by TitaneBoy** [comment]
Using `\'` doesn't not work unfortunetly.

Well ... Thank you for your answer and your great help...:-)
