### ISSUE TITLE
Issue with data-i18n-options

### ISSUE THREAD

**Issue by Netopya** [i18next/jquery-i18next#16]
Hello,
I am having difficulty using the data-i18n-options attribute on DOM elements to have variables interpolated. I tried to recreate the example from the readme however the options never seem to be passed from the attribute.
HTML:
`<div id="localize_me" data-i18n="myKey" data-i18n-options="{ 'a': 'b' }"></div>`

JavaScript:

```
jqueryI18next.init(i18next, $, {
  tName: 't', // --> appends $.t = i18next.t
  i18nName: 'i18n', // --> appends $.i18n = i18next
  handleName: 'localize', // --> appends $(selector).localize(opts);
  selectorAttr: 'data-i18n', // selector for translating elements
  targetAttr: 'i18n-target', // data-() attribute to grab target element to translate (if diffrent then itself)
  optionsAttr: 'i18n-options', // data-() attribute that contains options, will load/set if useOptionsAttr = true
  useOptionsAttr: true, // see optionsAttr
  parseDefaultValueFromContent: true // parses default values from content ele.val or ele.text
});

i18next.init({
  lng: 'en',
  debug: true,
  resources: {
    en: {
      translation: {
        "myKey": "hello world: {{a}}"
      }
    }
  }
});

$("#localize_me").localize();
```

Console output:

> i18next::interpolator: missed to pass in variable a for interpolating hello world: {{a}}

Thanks!

**Comment by jamuhl** [comment]
try:

`<div id="localize_me" data-i18n="myKey" data-i18n-options='{ "a": "b" }></div>`

the options need to be valid json

**Comment by Netopya** [comment]
Inverting the quotation marks (switching double-quotes for single-quotes and vice-versa) solved the issue. Thanks!

**Comment by bhaskerchari** [comment]
Hello jamuhl,

Your solution works but how we can do interpolation for dynamic values using the same approach. Do you have any thoughts?

Old ex:

<div id="localize_me" data-i18n="myKey" data-i18n-options='{ "a": "b" }></div>

New ex:

<div id="localize_me" data-i18n="myKey" data-i18n-options='{ "a": dynVariableValue }></div>

If I want to interpolate with some dynamic value which is defined in my javascript then what could be the approach? Especially we come across most commonly in case of using Knockoutjs framework and any client side databinding frameworks.

Thanks in advance,
Bhasker

**Comment by jamuhl** [comment]
for dynamic values it's easier to pass them like https://github.com/i18next/jquery-i18next#using-options-in-translation-function

`$("#btn1").localize(options);`

**Comment by jamuhl** [comment]
@bhaskerchari or not use jquery-i18next but some knockout binding of i18next or i18next directly

**Comment by bhaskerchari** [comment]
@jamuhl ,

I already had a look at the link https://github.com/i18next/jquery-i18next#using-options-in-translation-function but it works only for the static strings not for the dynamic one's.

Even I am thinking in the same direction to use some knockout binding of my own.

Thanks for your time.

**Comment by jamuhl** [comment]
What you mean by dynamic string. Not really understand what you try. Can you provide a sample?

**Comment by dixonsiu** [comment]
Hi,

I have the same problem.

Bad:

    var n = 10;
    $("#aDiv").localize({ count: n});

Okay:

    $("#aDiv").localize({ count: 10 });

**Comment by davoustp** [comment]
For the record, setting the `data-i18n-options`programmatically using jQuery works perfectly *but* you need to use `$(item).data("i18n-options", yourObject)` instead of `$(item).attr("data-i18n-options", yourObject)` or similar, as described in https://api.jquery.com/data/
