### ISSUE TITLE
Not working with zepto

### ISSUE THREAD

**Issue by fractalf** [i18next/jquery-i18next#17]
`<script src="https://cdnjs.cloudflare.com/ajax/libs/zepto/1.1.6/zepto.js" ></script>`

How hard is it to make it work with zepto?

**Comment by jamuhl** [comment]
more or less it just uses the selection part of jquery...so it should run on zepto. what errors do you get?

**Comment by fractalf** [comment]
Yea I thought it should work but it doesn't. No errors, just nothing happens when running localize().
Substitute the script above with the jquery in the example to reproduce.

I ended up skipping this plugin and just do a simple

```
$('*[data-i18next]').each(function() {
    var key = $(this).data('i18next');
    $(this).html(i18next.t(key));
})
```

it was actually enough for my simple web app

**Comment by jamuhl** [comment]
jquery-i18next uses $(sel).data() -> you will need to use a custom build of zepto providing the data API.

http://zeptojs.com/#download

**Comment by fractalf** [comment]
I already have the data API in Zepto, thats why my code above which I use instead of this plugin works :)
