### ISSUE TITLE
i18next.amd.withJQuery missing in 18next 3.x.x

### ISSUE THREAD

**Issue by sanjesh** [i18next/jquery-i18next#21]
In i18next 1.x.x there was a file named **i18next.amd.withJQuery** 
In 3.x.x version this is removed.
What is the alternative to this in latest version ?
Documentation doesn't specify anything about usage of i18next in amd modules(eg: require js)

**Comment by jamuhl** [comment]
Use the files provided on CDN like in the sample (just update to latest versions) https://github.com/i18next/jquery-i18next/blob/master/example/sample.html

or the file provided on the repo: https://github.com/i18next/jquery-i18next/blob/master/jquery-i18next.js

or the files coming by npm or bower

all come with UMD export
