### ISSUE TITLE
Load i18next on framework7 ajax loaded pages

### ISSUE THREAD

**Issue by rogerhnn** [i18next/jquery-i18next#22]
I am using i18next jquery version to localize the text. It works on each file if I click the button to change language (using localstorage to save the language option). But If I load another file in the view for example about page, it doesn't work.

Here is my i18next function with translation (language.js):

```
var itemslang = {
    "en": {
        "translation": {
          /* MENU */
          "About-Framework7": "About-Framework7",
          "Welcome-to-Framework7": "Welcome-to-Framework7",
        }
    },
        "br": {
        "translation": {
          /* MENU */
          "About-Framework7": "Sobre o Framework7",
          "Welcome-to-Framework7": "Bem Vindo ao Framework7",
        }
    }
};

$(document).ready(function() {
    var language = "en";
    if (localStorage.getItem("language") != null)
        language = localStorage.getItem("language");

    i18n.init({
        lng: language,
        resStore: itemslang,
        fallbackLng: "en"
    }, function(o) {
        $(document).i18n()
    }), $(".lang").click(function() {
        var o = $(this).attr("data-lang");

        localStorage.setItem("language", o);

        i18n.init({
            lng: o
        }, function(o) {
            $(document).i18n()
        })
    })
});
```

Can anyone point me on how to apply the translation on all pages and not just the first?

**Comment by jamuhl** [comment]
try using i18n.changeLanguage instead of init to change language. add debug=true on init of i18next to see more log output...

What you mean by: But If I load another file in the view for example about page, it doesn't work. ?!? how you load another view into view?

**Comment by rogerhnn** [comment]
I tried changing here:

```
$(document).ready(function() {
    var language = "en";
    if (localStorage.getItem("language") != null)
        language = localStorage.getItem("language");

    i18n.changeLanguage({
        lng: language,
        resStore: itemslang,
        fallbackLng: "en"
    }, function(o) {
        $(document).i18n()
    }), $(".lang").click(function() {
        var o = $(this).attr("data-lang");

        localStorage.setItem("language", o);

        i18n.changeLanguage({
            lng: o
        }, function(o) {
            $(document).i18n()
        })
    })
});
```

And I got that i18n.changeLanguage is not a function.

I mean, for example when you click a link in the demo of framework7 like "about" it loads another file into the view, the file "about.html" and the translation doesn't apply to that loaded file. It only works with the first page, and if I want it to work with another loaded file into the view, I need to click the button to change language again.

**Comment by jamuhl** [comment]
http://i18next.com/docs/api/#change-language `changeLanguage(lng, cb)`

on about.html you got the same script? not sure...must be related to your setup...but i don't see anything wrong there on first sight...would have to debug it.

you also can use https://github.com/i18next/i18next-browser-languageDetector so you don't have to take care for the localStorage stuff....

plus you should correct your code:

```
$(document).ready(function() {
    var language = "en";

    //####### same line or use {}
    if (localStorage.getItem("language") != null) language = localStorage.getItem("language");

    i18n.changeLanguage({
        lng: language,
        resStore: itemslang,
        fallbackLng: "en"
    }, function(t) {
        $(document).i18n();
    });

    //####### `;` on last line not `,`
    $(".lang").click(function() {
        var o = $(this).attr("data-lang");

        localStorage.setItem("language", o);

        i18n.changeLanguage(o, function(t) {
            $(document).i18n();
        });
    })
});
```

**Comment by jamuhl** [comment]
Must be related to framework7 you will need to call $(document).i18n() again when framework7 did load a file into view...a lot simpler would be you use https://github.com/i18next/i18nextify as that would take care for dom changes and translate on the fly

Even more simpler - just use http://locize.com our localization as a service tier.

**Comment by rogerhnn** [comment]
I corrected the code like you said, sorry I am a newbie with javascript, I did that with a lot of tutorials.

I don't know how to call $(document).i18n() again when framework7 did load a file into view.
And I have a lot of difficulties with javascript language. I just want to make everything work with i18next on all pages.

**Comment by jamuhl** [comment]
http://framework7.io/get-started/

see section "Scripts for specific page"

```
// Option 2. Using one 'pageInit' event handler for all pages:
$$(document).on('pageInit', function (e) {
  $(document).i18n();
});
```

**Comment by rogerhnn** [comment]
Thank you so much @jamuhl! It worked!

Also I forgot to call the my-app.js on the bottom of the body. Now it works on every page.

**Comment by jamuhl** [comment]
great to hear... 👍
