### ISSUE TITLE
Unable to use JQuery 3.1.1 together with jQuery-18next.

### ISSUE THREAD

**Issue by Jorricks** [i18next/jquery-i18next#24]
When using the sample code, with only an updated jquery version, it gives me there error that localize is not found. Do any of you have any idea how to fix this?

**Comment by jamuhl** [comment]
let me see...seems jquery changed the way own functions get appended.

**Comment by jamuhl** [comment]
nope...just updated the dependencies in sample - https://github.com/i18next/jquery-i18next/commit/15451c384b427624915c8ba73a55e7b741295c70

Still works here...idk...strange
