### ISSUE TITLE
 jqueryI18next.init is not a function(…)

### ISSUE THREAD

**Issue by aristot** [i18next/jquery-i18next#25]
I have an error :  jqueryI18next.init is not a function(…)
which seems be resolved ?

var i18next = require('i18next');
var i18nextInstance =  i18next.createInstance();
var jqueryI18next = require('jquery-i18next');
var initialize = function () {
var router, browse;

i18next.init({
    lng: 'fr', 
   
  }, function(err, t) {
    // for options see
    // https://github.com/i18next/jquery-i18next#initialize-the-plugin
    jqueryI18next.init(i18next, $);
    // start localizing, details:
    // https://github.com/i18next/jquery-i18next#usage-of-selector-function
    $("body").localize();
    browse = BrowseApp.initialize();
    return Backbone.history.start({ pushState: true });;
});

**Comment by jamuhl** [comment]
could you try with jquery-i18next@1.2.0

**Comment by aristot** [comment]
thanks this change works but I have a new bug

var template = _.template(NavTemplate)(data);
        this.$el.html(template);
        this.$el.i18n();
        Backbone.history.navigate('/hise', { trigger: true });
        return this;

nav_view.js:173 Uncaught TypeError: this.$el.i18n is not a function(…)

**Comment by jamuhl** [comment]
as long you did not override it should be `this.$el.localize();`

**Comment by jamuhl** [comment]
closing...feel free to reopen if still not solved.
