### ISSUE TITLE
parser for parseDefaultValueFromContent

### ISSUE THREAD

**Issue by jehon** [i18next/jquery-i18next#28]
Hello,

I see in the options the flag "parseDefaultValueFromContent".

That's great.

But how to use it when parsing the html/javascript files to build up the base translations files?

**Comment by jamuhl** [comment]
Sorry what you mean by: But how to use it when parsing the html/javascript files to build up the base translations files?

**Comment by jehon** [comment]
Hello,

Thanks for that quick reply.

I use "i18next-parser" to extract the strings to be translated into the "json" file. It took all my html and json, look for data-i18n attributes and _t() functions, and generate the json file.

Does this project use a similar generator to generate the json files, or does this project only manage the process after that generator?
If it does generate the json files, does it have that options in that phase?

Thanks

**Comment by jamuhl** [comment]
ok...now i understand. Parsing defaults here can be used in combination with the saveMissing feature of i18next which sends all keys not found via xhr (or similar, depending on your backend plugin) to your backend where you then can create a json file (eg. that is built in when using the i18next with node.js express or using http://locize.com localization service).

If you're using already i18next parser you can turn on this option as a fallback for the case when translation could not been loaded.

**Comment by jehon** [comment]
Ok, I understand.

Thanks for all the opportunities.

I will probably look to the parser for my specific point.

I am closing my question as it is not exactly in this scope.

Have a nice day
