### ISSUE TITLE
Uncaught TypeError: Cannot set property 't' of undefined

### ISSUE THREAD

**Issue by kieckhafer** [i18next/jquery-i18next#29]
We recently (today) starting seeing this error in our app: `Uncaught TypeError: Cannot set property 't' of undefined`

[It stems from this line of code](https://github.com/i18next/jquery-i18next/blob/master/src/index.js#L104).

Seems to have started right around when your `i18next` package was [updated earlier today](https://github.com/i18next/i18next/commit/5bd5f577831d8a2a8f7511a475f20e4cc7d29714) to version `7.1.0`, we were not seeing any errors prior to today.

When using `jquery-i18next` with Version `7.0.1` of `i18next`, everything works as expected.

**Comment by jamuhl** [comment]
hm, the only thing changed was additional plugin initialization...could you please show me your code where you add plugins? `i18next.use` calls?!?

Will provide a fix as soon i know what happens. thank you...

**Comment by kieckhafer** [comment]
This is how we're using it: https://github.com/reactioncommerce/reaction/blob/master/client/modules/i18n/startup.js

**Comment by jamuhl** [comment]
https://github.com/reactioncommerce/reaction/blob/master/client/modules/i18n/startup.js#L76

there is the mistake...no not use the jquery-i18next in i18next.

**Comment by kieckhafer** [comment]
We are still seeing the same errors when we remove the [line here](https://github.com/reactioncommerce/reaction/blob/master/client/modules/i18n/startup.js#L76).

The only solution that has worked has been to hardcode `i18next` to version `7.0.1` and not use version `7.1.0`.

**Comment by jamuhl** [comment]
could you please try i18next@7.1.1

**Comment by kieckhafer** [comment]
I believe I made a mistake when I took out that line of code. I think your solution actually is working. We are currently testing, I will close this issue if it works.

Thanks for your help!

**Comment by jamuhl** [comment]
great...just let me know if there is all ok...want to be sure all is running as expected...

**Comment by kieckhafer** [comment]
Works well, thanks for the help!
