### ISSUE TITLE
Upgrading from i18next.amd.withJQuery - TypeError in init

### ISSUE THREAD

**Issue by eb1** [i18next/jquery-i18next#30]
I'm attempting an upgrade from the older i18next.amd.withJQuery (v1.9) to jquery-i18next (1.2), and seem to be getting a TypeError when calling init:

My init call:

    var i18n  = require('i18n');
    ...
    i18n.init({
        lng: locale,
        debug: true,
        fallbackLng: 'en'
    }, function (err, t) {
        // Callback when i18next is finished initializing
        jqueryI18next.init(i18n, $);
    });

TypeError:

    lib/jquery-i18next.js:114 Uncaught TypeError: Cannot read property 'bind' of undefined
        at Object.init (lib/jquery-i18next.js:114)
        at initialize_i18n (js/Application.js:51)
    [...etc.]

It looks like it's having problems with the line:

    $[options.tName] = i18next.t.bind(i18next);

Am I missing something in my init call? Or maybe a shim in my require stuff?

**Comment by jamuhl** [comment]
just updated the sample to latest versions...can't reproduce there. Could you please provide a sample getting that error?

**Comment by jamuhl** [comment]
what version of i18next are you using? what does your i18n module look like?

**Comment by eb1** [comment]
Ack (smacks head against desk)... that's it! There are two modules to deal with now, instead of the rolled-up i18next.amd.withJQuery. Making sure I referred to both resolved the issue. Thanks!

For those upgrading that come across the same issue -- I'm using require.js and Jquery --  if you're using aliases, include both `i18next` and `jquery-i18next`. The first call is to the i18next module, the second is to the jquery-i18next one:

    paths: {
        'i18next': 'i18next.min',
        'jquery-i18next': 'jquery-i18next.min'
        ...
    },

...and then in the init call:

    var i18n = require('i18next'),
        jqueryi18n = require('jquery-i18next');

    i18n.init({
        lng: locale,
        debug: true,
        fallbackLng: 'en'
    }, function (err, t) {
         // Callback when i18next is finished initializing
         jqueryi18n.init(i18n, $);
    });

Thanks again, Jan!

**Comment by jamuhl** [comment]
great you figured out...
