### ISSUE TITLE
I can't load json files

### ISSUE THREAD

**Issue by danilocanel** [i18next/jquery-i18next#31]
Hello Team, I want to load json files but my script is not working:

backend: {loadPath: 'locales/{{ns}}/{{lng}}.json'} // is now working

[sample.html.zip](https://github.com/i18next/jquery-i18next/files/1062335/sample.html.zip)

**Comment by jamuhl** [comment]
If you add `resources` on init call - i18next won't load any translations from backend - as it's assuming you provided them on the init call. Remove the resources in init options and loading should work.
