### ISSUE TITLE
How can Key Fallback option be used for translations

### ISSUE THREAD

**Issue by gchandrababu** [i18next/jquery-i18next#32]
Hi,
I have started plying with language translation with i18next. Thanks a lot for this, it works too good for my pages. I'm able to use postprocessing also with sprintf and play around with multiple name spaces. 
I wanted to use key fallback(not language fallback) with my translations. 
my content goes like below.

<a href="#" class="listView" data-i18n="listView.buttonName"></a>

//locales/en/translation.json
{
"listView": {
    "flight": "FLIGHT",
    "tow": "TOW",
    "freeTxt": "FREE TEXT",
    "estp": "E-STOP",
    "newFltPln": "New Flight Plan",
    "aircftTyp": "Aircraft Type",
    "callSign": "Call Sign",
   "buttonName": "Save Data"
  "errMsg": "Can't Translate"
}
}

//initialization goes something like this 
	i18next
	  .use(i18nextXHRBackend)
	  .init({
		lng: en,
		fallbackLng: ['de', 'en'],
		debug: true,
		ns: ['translation'],      
   backend: {
		loadPath: '../../../locales/{{lng}}/{{ns}}.json',
		crossDomain: true
			}
      }, function(err, t) {
        jqueryI18next.init(i18next, $);
        $(.listView).localize();
      });

my requirement is , if I want to pass a fallback key(e.g errMsg) along with translation key like i found as below in documentation,  how should I pass it? 

i18next.t([`error.${error}`, 'error.unspecific'])

Thank you for your time.
Regards,
Chandra

**Comment by jamuhl** [comment]
currently jquery-i18next does not support fallbackKeys on the `data-i18n` attribute.

Adding that would need some addition here: https://github.com/i18next/jquery-i18next/blob/master/src/index.js#L29 doing an additional `key.split` to get an array of keys.

PR would be very welcome.

**Comment by gchandrababu** [comment]
Thank you for the update. 
Let me see if I can be able to

**Comment by jamuhl** [comment]
Awesome...thank you.
