### ISSUE TITLE
localize not defined when .use(i18nextBrowserLanguageDetector) is called

### ISSUE THREAD

**Issue by dixonsiu** [i18next/jquery-i18next#33]
Hi,

I have upgraded my i18next from 1.11.1 to 8.4.3 and use the following plugins. It kept telling me localize is not defined. What should I do?

1. i18nextXHRBackend
1. i18nextBrowserLanguageDetector
1. jqueryI18next

My init routine:

        i18next
            .use(i18nextXHRBackend)
            .use(i18nextBrowserLanguageDetector)
            .init({
                fallbackLng: 'en',
                debug: true,
                backend: {
                    // load from i18next-gitbook repo
                    loadPath: './locales/{{lng}}/translation.json',
                    crossDomain: true
                }
            }, function(err, t) {
                // for options see
                // https://github.com/i18next/jquery-i18next#initialize-the-plugin
                jqueryI18next.init(i18next, $, {
                	handleName: "localize",
                	selectorAttr: "data-i18n"
                });
                // start localizing, details:
                // https://github.com/i18next/jquery-i18next#usage-of-selector-function
                updateContent();
            });

        function updateContent() {
            $('title').localize();
            $('[data-i18n]').localize();
        }

**Comment by dixonsiu** [comment]
Hi,

Just found that if I move the jqueryI18next.init call to updateContent, it works. Probably timing problem during initialization.

Regards,
Dixon

**Comment by jamuhl** [comment]
do you get any errors or warnings in console...your configuration should work...basically the same we have in the example.

**Comment by jamuhl** [comment]
Or do you call updateContent somewhere else outside of the init callback - that would explain it.

**Comment by dixonsiu** [comment]
Hi Jan,

The error I got when calling jqueryI18next's init directly inside the i18next init callback is as follow:
"... localize function is not defined". And I didn't call updateContent anywhere else.

However, even with the old sources, I can't reproduce the problem anymore. Strange. Maybe there is a cache problem with Chrome. I will close the issue for now. If I encounter it again, I will reopen it.

Thank you very much for checking on my question.

Regards,
Dixon

**Comment by jamuhl** [comment]
strange...please reopen if you encounter it again...
