### ISSUE TITLE
When there is no default value when binding to an attribute it inserts the key instead of blank

### ISSUE THREAD

**Issue by peterlukerow** [i18next/jquery-i18next#36]
Say you have the HTML:
`<input type="text" data-i18l="[title]namespace.key.to.use" />`

Now say you have a default of en-GB which does not have a value for that namespace/key and you initialise i18l to use German version of resources (de) which does have the namespace/key.

When you view the page with German language, all is well and you get a text input displayed and when you hover over it you get a tooltip as specified in the title attribute that you localize() with.

The bug happens when you switch to the English language (in this example). Because it does not have the above namespace/key when you hover over the text input displayed on the page you get a tooltip that says "namespace.key.to.use".

I can't see when this behaviour would be useful in the instance where the key doesn't exist it should just add the title attribute with no content not use the key as the text. This is what it does in other cases, e.g. if you have `<h2 data-i18l="namespace.page.title"></h2>`, and the key doesn't exist you'd end up with an empty `<h2>` tag not `<h2 data-i18l="namespace.page.title">namespace.page.title</h2>`

**Comment by jamuhl** [comment]
are you sure...i think the behaviour is consistent - if there is no text found it will show the key instead -> to show devs, translators, who ever -> you forgot something: while an empty string just does not attracts attention for a mistake.

there are tons of options reading the docs:

1) set a fallbackLng (so if no translation is found the sourcelanguage / fallback is shown
2) override parseMissingKeyHandler: https://www.i18next.com/configuration-options.html#missing-keys

**Comment by peterlukerow** [comment]
Yes I'm sure. In my test I had fallback language, but if your current and fallback language are the same then obviously that has no effect.

Plus it is not consistent, see my 2nd example, I'll repeat it here, if you have `<h2 data-i18l="namespace.page.title"></h2>` and both the current and fallback language don't have that defined then you get `<h2 data-i18l="namespace.page.title"></h2>` in your page, **you do not get** `<h2 data-i18l="namespace.page.title">namespace.page.title</h2>` as you suggest. The only time it behaves like that (which is why I raised this bug) is when you are trying to set the value of an attribute with it.

If the plugin is suppose to work as you say then the bug is the other way around.

I guess I should admit that in the test scenario that I'm investigating using this for we are not using this for translation per say, but as a way for customers to change text on a page without us having to add special fields for them. We simply add in the markup for the page and if they want to override the default then so be it we just add a resource JSON file for that namespace for their "language", but if they don't or there is no default you don't get pointless key text.

**Comment by jamuhl** [comment]
ok...sorry...now found the cause. Hard to remember special cases for all the framework integrations of i18next ;)

on h2 it does show empty string as it takes by default the current initial value of the h2 as defaultValue for translations -> so it shows '' instead of key (while showing key would be default in pure i18next).

you can set 'parseDefaultValueFromContent: false' https://github.com/i18next/jquery-i18next#initialize-the-plugin 

sample -> https://jsfiddle.net/yueLnwqz/

But anyway you want the '' anyway -> see https://jsfiddle.net/apnd4dnx/ uses the parseMissingKeyHandler

**Comment by peterlukerow** [comment]
Excellent, thanks  for the jsFiddles, :)
