### ISSUE TITLE
i18next with razor engine

### ISSUE THREAD

**Issue by sapnavyas** [i18next/jquery-i18next#37]
I am using jQuery i18next plugin for my asp.net mvc application with razor engine view. 
somehow my UI rendering is slow. I believe the way i18n works is it traverse through DOM elements and replaces "data-i18n" attributes. so until my DOM is ready it is not replacing the elements text using i18next which is causing delay where server is talking time to return data to UI. so until data is available with UI, my localization is put on hold. is there any way to overcome this delay?

**Comment by jamuhl** [comment]
i18next itself has no check for dom ready - it starts as soon init is done and if using xhr translations are loaded. If this has to be slow also depends on how fast you serve your translations.

Eg. check https://locize.com do you get any recognizable slowdown

**Comment by sapnavyas** [comment]
I am using local storage to cache the translation returned from the server. so translation is available at the first page load. but it is taking time to translate in subsequent loads as well. 

I am using the following plugins ,

   i18next.use(i18nextLocalStorageBackend);
    i18next.use(i18nextCustomCallbackBackend);
    i18next.use(i18nextChainedBackend);
	i18next.use(i18nextBrowserLanguageDetector);
    i18next.init(i18nOptions, function (err, t) {
        jqueryI18next.init(i18next, $);
        $("*[data-i18n]").localize();
    });

could init take longer in this case??

**Comment by jamuhl** [comment]
is the localstorage backend the first backend in the backends list in the chainedbackend?

are your pages overly huge?

**Comment by sapnavyas** [comment]
this is chainedbackend options

var backend = {
    backends: [
        i18nextLocalStorageBackend,  
        i18nextCustomCallbackBackend  
    ],
    backendOptions: [{

        enabled: true,
        prefix: 'i18next_res_',
        expirationTime: 1 * 24 * 60 * 60 * 1000,

    }, {
        // Callback used when loading a single resource.
        customLoad: loadLocalesViaApi
    }]
}

My pages are not much huge. I've used data-i18n attributes in 30-35 elements on an average on a single page.

**Comment by jamuhl** [comment]
could you provide a sample on jsfiddle or similar to try to reproduce...really shouldn't be noticable slow

**Comment by sapnavyas** [comment]
Sorry, it cant be reproduced in fiddle as it has many server side controls. 

attaching snapshot of how it looks when rendering UI. if you look at the Tab strip, it loads title after a pause of 2-3 seconds.  same in table column header in white background. It looks like HTML elements are available but not innerHTML. 
![i18n](https://user-images.githubusercontent.com/37228408/41059459-a1d5103a-699a-11e8-948f-de37be1546a9.png)

**Comment by jamuhl** [comment]
Did you set debug: true on i18next.init and checked console output for warnings...looks like something is going wrong

**Comment by sapnavyas** [comment]
This is how my console looks and I think it looks good. despite of a sync xhr warning.



![console](https://user-images.githubusercontent.com/37228408/41060135-a95606f0-699c-11e8-981b-8f15879bf96f.png)

**Comment by jamuhl** [comment]
your synchronous request blocks rendering

bad idea

**Comment by sapnavyas** [comment]
hmmm..  in this case, it should block only when request is made for the first time. after locales are cached in local storage, it is not even making that sync call. 

also is there any other way around ? 
because it is not a pure front end application, I dont have control over the bootstrapping. .Net mvc loads bundles even if my locales are not loaded which would obviously give errors.

**Comment by jamuhl** [comment]
i left .net long ago, so i'm not up to date how that stack is used nowadays.

So honestly if eg. https://locize.com is not slow for you - it's not i18next. I guess anyway it's not i18next - as endless sites are using it.

I just can say try to isolate the problem...start by making a simple standalone fiddle for i18next to see the bottleneck is not i18next. As a base you might try https://jsfiddle.net/jamuhl/ferfywyf/#tabs=js,result,html

**Comment by jamuhl** [comment]
eventual search help over at stackoverflow - guess i'm out of options to help without able to reproduce your problem....sorry

**Comment by sapnavyas** [comment]
yes makes sense! anyways thanks for your time, I will try to reproduce the issue in fiddle. 
Thank you!
