### ISSUE TITLE
Cannot read property 'parseDefaultValueFromContent' of undefined

### ISSUE THREAD

**Issue by sqal** [i18next/jquery-i18next#4]
Hi. Like the title says, I am still getting this error in the console. I am using i18next version 2.0.22 with jquery-i18next version 0.0.10 and my setup looks like this:

```
var i18options = {
    lng: 'en',
    fallbackLng: 'en',
    backend: {
        loadPath: 'locales/{{ lng }}.json'
    }
};

i18next
    .use(i18nextXHRBackend)
    .init(i18options, function(err, t) {

        i18nextJquery.init(i18next, $, {
            useOptionsAttr: true,
            parseDefaultValueFromContent: true
        });

        $('body').localize();

    });
```

When i set `useOptionsAttr` to `false` the issue is gone, but I need this option so that does not solves my problem. Is this coused by some bug in the plugin or maybe I am doing something wrong? Here is how i try to translate some element one the page:

```
<div data-i18n="[html]fileSize" data-i18n-options='{ "size": "110 KB" }'>File size: <strong>110 KB</strong></div>
```

en.json

```
{
  "fileSize": "File size: <strong>__size__</strong>"
}
```

Thanks for the help! :)

**Comment by jamuhl** [comment]
can you try jquery-i18next v0.0.11

**Comment by sqal** [comment]
@jamuhl 

Console is now clear but still something is wrong. Still does not parse values passed in options attribute:

**Comment by jamuhl** [comment]
can you $(yourEle).data('data-i18n-options') -> might be non valid json

**Comment by sqal** [comment]
Nope, this way doesn´t work either.Perhaps this is related to how jQuery converts this attribute (camelCase), look at the screenshot, data is there: http://prntscr.com/9unfdy

btw. i use jQuery 2.1.4

**Comment by jamuhl** [comment]
sorry my wrong should be $(yourEle).data('i18n-options') --> try v0.0.13

i always forgot...$sel.data appends data- to the attribute to read out...

**Comment by sqal** [comment]
Yeah. v.0.0.13 works as it should be. Thank you, really appreciate quick help on this :)

**Comment by jamuhl** [comment]
great...

**Comment by sqal** [comment]
although..  when i change the language using changeLanguage, values from data-i18n-options are not rendered again :( just other text from json.

**Comment by jamuhl** [comment]
changeLanguage does not trigger a rerender...it does only change the language set on i18next. you need to call `$('body').localize();` again!

**Comment by sqal** [comment]
@jamuhl yes, I know. i am doing localize() inside changeLanguage callback :) all the text is translated correctly.. but as I said.. values from options are not rendered after that, they're rendered only first time on page load.

**Comment by jamuhl** [comment]
strange...will check again tomorrow....

**Comment by jamuhl** [comment]
sorry for the troubles...could you try v0.0.14?

**Comment by sqal** [comment]
Fixed :) Thank you.

**Comment by biroplane** [comment]
How did you solve it? i'm trying with Handlebars rendered templates and selctpickr option but it doesen't change anything....
