### ISSUE TITLE
complex replacement i18n vs i18next

### ISSUE THREAD

**Issue by ssuess** [i18next/jquery-i18next#41]
I am evaluating the differences and ease of use between jQuery i18n and i18next, and it seems that it is much less work in certain cases to translate using i18n, but perhaps I am missing something. For example, how would I write this i18n phrase:

`var phrase = $1 has $2 {{plural:$2|kitten|kittens}}. {{gender:$3|He|She}} loves to play with {{plural:$2|it|them}}.`

`$.i18n( phrase, 'john', 2, 'male');`

in i18next? What is good about this way of writing (i18n) is that the context and entire sentence is clear, but I am not sure at all how I would achieve the same contextual clarity using i18next in a single translated line with 3 variables (1 normal variable, one plural, and one gender). Can you tell me how I might achieve the same using i18next syntax?

**Comment by jamuhl** [comment]
https://www.i18next.com/translation-function/context#combining-with-plurals

**Comment by ssuess** [comment]
described and answered more thoroughly here: https://github.com/i18next/i18next/issues/1309
