### ISSUE TITLE
How can I use HTML tags?

### ISSUE THREAD

**Issue by desmeit** [i18next/jquery-i18next#42]
I added 

 interpolation: {'escapeValue': false}

to init for showing an `&` instead of `&amp;` in my json.
I added it like this to my html:

`<span data-i18n="html.t5"></span>`

But it is not working. It shows the raw `&amp;`.
How can I show HTML within my json?

**Comment by jamuhl** [comment]
https://github.com/i18next/jquery-i18next#set-innerhtml-attributes

**Comment by desmeit** [comment]
very nice. thank you.
