### ISSUE TITLE
i18nextHttpBackend looking 'locales' folder under main directory of the server rather than working directory

### ISSUE THREAD

**Issue by KeremArdicli** [i18next/jquery-i18next#43]
Using i18next with jQuery plugin. It is working fantastically. However, while trying to use 'i18nextHttpBackend' solution, i18next is loooking 'locales' folder under server main directory.

For example:
I am wroking at localhost/my-app
i18next.js file is located at localhost/my-app/js/i18next.js
my translation files are under at localhost/my-app/locales/en/translation.json

i18next is looking for translation.json files under localhost/locales which i believe is wrong. Even if there is an option to change it, it is not documented on jQuery page. And this should not be the default behaviour.

**Comment by adrai** [comment]
You can define a different loadPath option: https://github.com/i18next/i18next-http-backend#backend-options

**Comment by adrai** [comment]
Also described here in this blog post: https://locize.com/blog/jquery-i18next/#separate
<img width="938" alt="image" src="https://user-images.githubusercontent.com/1086194/216067737-64bc7226-5654-4ed9-b5a4-e1dc09a9051f.png">

**Comment by KeremArdicli** [comment]
Would be nice to see it on actual page rather than blog post.

https://locize.com/blog/jquery-i18next/

Thanks again.

**Comment by adrai** [comment]
https://github.com/i18next/i18next-http-backend/blob/10e19c5c504e25771a5a36496a80a706ab561955/example/jquery/index.html#L28
