### ISSUE TITLE
Is there a executable demo? 

### ISSUE THREAD

**Issue by jackple** [i18next/jquery-i18next#5]
I just can not know how to use it...

**Comment by sowacx** [comment]
There is: https://github.com/i18next/jquery-i18next/blob/master/example/sample.html

**Comment by ganpats** [comment]
> There is: https://github.com/i18next/jquery-i18next/blob/master/example/sample.html

path changed to: https://github.com/i18next/jquery-i18next/blob/master/example/simple/sample.html
