### ISSUE TITLE
HTML from options attribute is appended as text regardless of the [html] prefix 

### ISSUE THREAD

**Issue by sqal** [i18next/jquery-i18next#6]
When I was using version of 1.x of i18next i had this kind of element on my site:

```
<p data-i18n="[html]agreeTos" data-i18n-options='{"tosLink":"<a href=\"#\" target=\"_blank\">$t(agreeTosLinkText)</a>"}'></p>
```

and it translated the text with clickable link at the end. But in current version of the plugin this thing is broken. I get the link rendered as plain text, not the actual link. I am not sure what changed and if I am still doing it correctly, so i would appreciate any help in this matter. Thanks.

**Comment by jamuhl** [comment]
by default interpolation values get escaped...safes you from xss.

you can override this: http://i18next.com/docs/options/#interpolation-options --> `escapeValue: false`

can be specified on init or in calling t options (data-i18n-options):

```
i18next.init({
  interpolation: {
    escapeValue: false
  }
});
```

**Comment by sqal** [comment]
Ok then. I somehow missed this option. Thanks for clarifying that for me.Have a nice day :)
