### ISSUE TITLE
upgrading from v1

### ISSUE THREAD

**Issue by prtome** [i18next/jquery-i18next#7]
hello,
I have been using the previous version which called the translations as $.t('key.value')

I am completely at lost as how do I change these. 
do I understand well that if I was using
<th> $.t('key.value') </th>
I must use 
<th data-i18n="key.value"></th> ?

giving all headers (or the top div ?) a class and the $(.myclass).localize(); 

I use jQuery.validation and I have additional methods:
$.validator.addMethod('le', function(value, element, param) {
      return this.optional(element) || parseInt(value) <= parseInt($(param).val())
},$.t('invalid_value'));

How do I change it there ?

Sorry if this is not the correct place to ask, I am completely lost in how to use this new version vs what I have already coded
Thanks for any help or pointers to the docs

**Comment by jamuhl** [comment]
it is all the same as before, just it is now .localize() was before .i18n(). all you need is proper initialized i18next instance passed to init. 

see the example folder in this repo

**Comment by prtome** [comment]
Thanks but I do not understand.
I have never use did the way the example is shown.
My init is as follows:
i18n.init({ lng: $("#user_lang").val(),fallbackLng : 'it' }, function() {

and from here on, I have all my query/js script. When I need to use the translations, I use $.t('key.value') 

My understanding is that I should now do
i18next.init({ lng: $("#user_lang").val(),fallbackLng : 'it' }, function() {
i18nextJquery.init(i18next, $, {  tName: 't'});

and I can continue using $.t
did I understood correctly ? (obviously not, because not working)
Sorry if this is basic, but I am really confused today 
Thanks

**Comment by prtome** [comment]
thanks - I give up for now, I really don't get it. 
 I will stay for now in v1 which I control better

**Comment by jamuhl** [comment]
as i see, all you used until now is the $.t function. the jquery integration always had the $(selector).localize() for instrumenting the html pages via attribute data-i18n.

basically if you just need the t function you can take v2 of i18next and set both json and api compatibility to v1 like described on migration guide. from there you can use i18next.t or append that function to $ again.

**Comment by prtome** [comment]
thanks, yes this is all I need. I will have to understand how to move all my code to the new version, but it is going to take a lot of time, because there are place where I don't know how to use the data-i18n
what is the use of 
  tName: 't', // --> appends $.t = i18next.t 
in i18nextjQuery initialisation

**Comment by jamuhl** [comment]
like said...

`and from here on, I have all my query/js script. When I need to use the translations, I use $.t('key.value')`

=> you don't need the jquery-i18next part, only i18next's t function.

use the compatibility flags: http://i18next.com/docs/migration/#v1-11-x--v2-0-0-comp

add plugins for languageDetection, xhr loading:
https://github.com/i18next/i18next-xhr-backend
https://github.com/i18next/i18next-browser-languageDetector

other plugins: http://i18next.com/docs/ecosystem/

to append t function to jquery:

```
$.t = function() {
  i18next.t.apply(i18next, arguments);
};
```

**Comment by prtome** [comment]
Thanks for your patient explanations. I tried, but still cannot get this working. It cannot load my files, gives me a 550 error, i18next::backendConnector: loading namespace translation for language it failed failed loading /locales/it/translation.json
The files exist. 
Do you have an example of using i18next-xhr-backend with a node server ? thanks
