### ISSUE TITLE
problem on safari with 

### ISSUE THREAD

**Issue by prtome** [i18next/jquery-i18next#8]
hello
first, thanks for your help, I finally understood and got everything working.
I have now a problem due to my lack of knowledge of JS I presume
I copied my code from the docs

```
    i18next.use(i18nextXHRBackend).init({ 
        backend: {
       loadPath: '/locales/{{lng}}/{{ns}}.json'
   },
    long:'it',fallbackLng : 'it' }, (err, t) => {     
```

Everything works perfectly on Firefox and Chrome, but fails on Safari with the following error:

```
SyntaxError: Unexpected token '>'
```

which is the =>

I don't know how I should change that, could you point me in the correct direction ? thank you

**Comment by jamuhl** [comment]
change it to:

```
 i18next.use(i18nextXHRBackend).init({ 
        backend: {
       loadPath: '/locales/{{lng}}/{{ns}}.json'
   },
    long:'it',fallbackLng : 'it' }, function (err, t) {
   }
```

() => {} is arrow function and might not work in safari -> if you like to use latest es2015 you need to transpile that for browsers not supporting it by using https://babeljs.io/
