### ISSUE TITLE
console warning in firefox

### ISSUE THREAD

**Issue by prtome** [i18next/jquery-i18next#9]
Hello
(on Mac 10.11.3, latest firefox) when using firefox I got the following warning

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create

i18next.min.js

This does not appear when running on Chrome.

**Comment by jamuhl** [comment]
can be ignores...just a firefox 'stupidity': http://stackoverflow.com/questions/33858349/fixing-mutating-the-prototype-of-an-object-in-babeljs-6

caused by babel transpile. Nothing to worry about.
